server:
  port: 1111
  servlet:
    context-path: /
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server

