dubbo:
  protocol:
    name: dubbo
    port: -1
    host: localhost
  registry:
    address:  spring-cloud://localhost:8848
  monitor:
    default: false
  scan:
    base-packages: cn.lee.jason.dubbo.provider
eureka:
  client:
    enabled: false
server:
  port: 8085
  servlet:
    context-path: "/dubbo-provider"
spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848