server:
  port: 8086
  servlet:
    context-path: "/dubbo-consumer"
spring:
  application:
    name: dubbo-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.196:8848
dubbo:
  protocol:
    port: -1
    host: localhost
    serialization: kryo
    optimizer: cn.lee.jason.dubbo.api.SerializationOptimizerImpl
  registry:
    address: spring-cloud://192.168.1.196:8848
  cloud:
    subscribed-services: dubbo-provider
eureka:
  client:
    enabled: false

