server:
  port: 8087
  servlet:
    context-path: "/dubbo-consumer"
spring:
  application:
    name: dubbo-consumer2
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.196:8848
dubbo:
  protocol:
    host: localhost
    port: -1
  registry:
    address: spring-cloud://192.168.1.196:8848
  cloud:
    subscribed-services: dubbo-provider
eureka:
  client:
    enabled: false

